# Generated by Django 5.2.3 on 2025-09-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikasi', '0002_mahasiswa_jurusan_mahasiswa_nim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='nim',
            field=models.CharField(null=True, unique=True),
        ),
    ]
