# Generated by Django 5.2.6 on 2025-09-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikasi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='jurusan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='nim',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
