# Generated by Django 5.2.7 on 2025-10-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drfpost',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover/'),
        ),
    ]
